name: Build and Deploy Switchbot WatchKit App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Make script executable
      run: chmod +x build-and-upload.sh
      
    - name: Build and Upload to TestFlight
      env:
        APPSTORE_API_KEY_ID: ${{ vars.APPSTORE_API_KEY_ID }}
        APPSTORE_ISSUER_ID: ${{ vars.APPSTORE_ISSUER_ID }}
        APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      run: ./build-and-upload.sh
      
    - name: Upload build logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: build/export_full.log
